name: employee_forums
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.3.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
